export const ROUTER_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  MONITORING: "monitoring",
  DEVICES: 'devices',
  CPUS: "/devices/cpus",
  GPUS: "/devices/gpus",
  GPU: ":gpuId",
  RIGS: 'rigs',
  RIG: 'rigs/:rigId',
  RIG_GPUS: 'gpus',
  RIG_CPUS: 'cpus',
  RIG_MOTHERBOARD: 'motherboard',
  RIG_INTERNET: 'internet',
  RIG_HDDS: 'hdds',
  STATISTIC: 'statistic',
  FLIGHT_SHEETS: 'flight-sheets',
  PRESETS: 'presets',
  CRYPTOS: 'cryptos',
  WALLETS: 'wallets',
  POOLS: 'pools',
  PROFILE: 'profile',
  FEEDBACK: 'feedback'
} as const;