/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GuardLayoutImport } from './routes/_guard-layout'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthRegistrationImport } from './routes/_auth/registration'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as GuardLayoutSetupPresetsImport } from './routes/_guard-layout/setup/presets'
import { Route as GuardLayoutSetupFlightSheetsImport } from './routes/_guard-layout/setup/flight-sheets'
import { Route as GuardLayoutMiningWalletsImport } from './routes/_guard-layout/mining/wallets'
import { Route as GuardLayoutMiningPoolsImport } from './routes/_guard-layout/mining/pools'
import { Route as GuardLayoutMiningMinersImport } from './routes/_guard-layout/mining/miners'
import { Route as GuardLayoutMiningCryptocurrenciesImport } from './routes/_guard-layout/mining/cryptocurrencies'
import { Route as GuardLayoutMiningAlgorithmsImport } from './routes/_guard-layout/mining/algorithms'
import { Route as GuardLayoutDevicesGpusImport } from './routes/_guard-layout/devices/gpus'
import { Route as GuardLayoutDevicesCpusImport } from './routes/_guard-layout/devices/cpus'

// Create Virtual Routes

const GuardLayoutMonitoringLazyImport = createFileRoute(
  '/_guard-layout/monitoring',
)()

// Create/Update Routes

const GuardLayoutRoute = GuardLayoutImport.update({
  id: '/_guard-layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GuardLayoutMonitoringLazyRoute = GuardLayoutMonitoringLazyImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => GuardLayoutRoute,
} as any).lazy(() =>
  import('./routes/_guard-layout/monitoring.lazy').then((d) => d.Route),
)

const AuthRegistrationRoute = AuthRegistrationImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const GuardLayoutSetupPresetsRoute = GuardLayoutSetupPresetsImport.update({
  id: '/setup/presets',
  path: '/setup/presets',
  getParentRoute: () => GuardLayoutRoute,
} as any)

const GuardLayoutSetupFlightSheetsRoute =
  GuardLayoutSetupFlightSheetsImport.update({
    id: '/setup/flight-sheets',
    path: '/setup/flight-sheets',
    getParentRoute: () => GuardLayoutRoute,
  } as any)

const GuardLayoutMiningWalletsRoute = GuardLayoutMiningWalletsImport.update({
  id: '/mining/wallets',
  path: '/mining/wallets',
  getParentRoute: () => GuardLayoutRoute,
} as any)

const GuardLayoutMiningPoolsRoute = GuardLayoutMiningPoolsImport.update({
  id: '/mining/pools',
  path: '/mining/pools',
  getParentRoute: () => GuardLayoutRoute,
} as any)

const GuardLayoutMiningMinersRoute = GuardLayoutMiningMinersImport.update({
  id: '/mining/miners',
  path: '/mining/miners',
  getParentRoute: () => GuardLayoutRoute,
} as any)

const GuardLayoutMiningCryptocurrenciesRoute =
  GuardLayoutMiningCryptocurrenciesImport.update({
    id: '/mining/cryptocurrencies',
    path: '/mining/cryptocurrencies',
    getParentRoute: () => GuardLayoutRoute,
  } as any)

const GuardLayoutMiningAlgorithmsRoute =
  GuardLayoutMiningAlgorithmsImport.update({
    id: '/mining/algorithms',
    path: '/mining/algorithms',
    getParentRoute: () => GuardLayoutRoute,
  } as any)

const GuardLayoutDevicesGpusRoute = GuardLayoutDevicesGpusImport.update({
  id: '/devices/gpus',
  path: '/devices/gpus',
  getParentRoute: () => GuardLayoutRoute,
} as any)

const GuardLayoutDevicesCpusRoute = GuardLayoutDevicesCpusImport.update({
  id: '/devices/cpus',
  path: '/devices/cpus',
  getParentRoute: () => GuardLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_guard-layout': {
      id: '/_guard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/registration': {
      id: '/_auth/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthRegistrationImport
      parentRoute: typeof AuthImport
    }
    '/_guard-layout/monitoring': {
      id: '/_guard-layout/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof GuardLayoutMonitoringLazyImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/devices/cpus': {
      id: '/_guard-layout/devices/cpus'
      path: '/devices/cpus'
      fullPath: '/devices/cpus'
      preLoaderRoute: typeof GuardLayoutDevicesCpusImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/devices/gpus': {
      id: '/_guard-layout/devices/gpus'
      path: '/devices/gpus'
      fullPath: '/devices/gpus'
      preLoaderRoute: typeof GuardLayoutDevicesGpusImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/mining/algorithms': {
      id: '/_guard-layout/mining/algorithms'
      path: '/mining/algorithms'
      fullPath: '/mining/algorithms'
      preLoaderRoute: typeof GuardLayoutMiningAlgorithmsImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/mining/cryptocurrencies': {
      id: '/_guard-layout/mining/cryptocurrencies'
      path: '/mining/cryptocurrencies'
      fullPath: '/mining/cryptocurrencies'
      preLoaderRoute: typeof GuardLayoutMiningCryptocurrenciesImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/mining/miners': {
      id: '/_guard-layout/mining/miners'
      path: '/mining/miners'
      fullPath: '/mining/miners'
      preLoaderRoute: typeof GuardLayoutMiningMinersImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/mining/pools': {
      id: '/_guard-layout/mining/pools'
      path: '/mining/pools'
      fullPath: '/mining/pools'
      preLoaderRoute: typeof GuardLayoutMiningPoolsImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/mining/wallets': {
      id: '/_guard-layout/mining/wallets'
      path: '/mining/wallets'
      fullPath: '/mining/wallets'
      preLoaderRoute: typeof GuardLayoutMiningWalletsImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/setup/flight-sheets': {
      id: '/_guard-layout/setup/flight-sheets'
      path: '/setup/flight-sheets'
      fullPath: '/setup/flight-sheets'
      preLoaderRoute: typeof GuardLayoutSetupFlightSheetsImport
      parentRoute: typeof GuardLayoutImport
    }
    '/_guard-layout/setup/presets': {
      id: '/_guard-layout/setup/presets'
      path: '/setup/presets'
      fullPath: '/setup/presets'
      preLoaderRoute: typeof GuardLayoutSetupPresetsImport
      parentRoute: typeof GuardLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistrationRoute: typeof AuthRegistrationRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistrationRoute: AuthRegistrationRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuardLayoutRouteChildren {
  GuardLayoutMonitoringLazyRoute: typeof GuardLayoutMonitoringLazyRoute
  GuardLayoutDevicesCpusRoute: typeof GuardLayoutDevicesCpusRoute
  GuardLayoutDevicesGpusRoute: typeof GuardLayoutDevicesGpusRoute
  GuardLayoutMiningAlgorithmsRoute: typeof GuardLayoutMiningAlgorithmsRoute
  GuardLayoutMiningCryptocurrenciesRoute: typeof GuardLayoutMiningCryptocurrenciesRoute
  GuardLayoutMiningMinersRoute: typeof GuardLayoutMiningMinersRoute
  GuardLayoutMiningPoolsRoute: typeof GuardLayoutMiningPoolsRoute
  GuardLayoutMiningWalletsRoute: typeof GuardLayoutMiningWalletsRoute
  GuardLayoutSetupFlightSheetsRoute: typeof GuardLayoutSetupFlightSheetsRoute
  GuardLayoutSetupPresetsRoute: typeof GuardLayoutSetupPresetsRoute
}

const GuardLayoutRouteChildren: GuardLayoutRouteChildren = {
  GuardLayoutMonitoringLazyRoute: GuardLayoutMonitoringLazyRoute,
  GuardLayoutDevicesCpusRoute: GuardLayoutDevicesCpusRoute,
  GuardLayoutDevicesGpusRoute: GuardLayoutDevicesGpusRoute,
  GuardLayoutMiningAlgorithmsRoute: GuardLayoutMiningAlgorithmsRoute,
  GuardLayoutMiningCryptocurrenciesRoute:
    GuardLayoutMiningCryptocurrenciesRoute,
  GuardLayoutMiningMinersRoute: GuardLayoutMiningMinersRoute,
  GuardLayoutMiningPoolsRoute: GuardLayoutMiningPoolsRoute,
  GuardLayoutMiningWalletsRoute: GuardLayoutMiningWalletsRoute,
  GuardLayoutSetupFlightSheetsRoute: GuardLayoutSetupFlightSheetsRoute,
  GuardLayoutSetupPresetsRoute: GuardLayoutSetupPresetsRoute,
}

const GuardLayoutRouteWithChildren = GuardLayoutRoute._addFileChildren(
  GuardLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof GuardLayoutRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/registration': typeof AuthRegistrationRoute
  '/monitoring': typeof GuardLayoutMonitoringLazyRoute
  '/devices/cpus': typeof GuardLayoutDevicesCpusRoute
  '/devices/gpus': typeof GuardLayoutDevicesGpusRoute
  '/mining/algorithms': typeof GuardLayoutMiningAlgorithmsRoute
  '/mining/cryptocurrencies': typeof GuardLayoutMiningCryptocurrenciesRoute
  '/mining/miners': typeof GuardLayoutMiningMinersRoute
  '/mining/pools': typeof GuardLayoutMiningPoolsRoute
  '/mining/wallets': typeof GuardLayoutMiningWalletsRoute
  '/setup/flight-sheets': typeof GuardLayoutSetupFlightSheetsRoute
  '/setup/presets': typeof GuardLayoutSetupPresetsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof GuardLayoutRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/registration': typeof AuthRegistrationRoute
  '/monitoring': typeof GuardLayoutMonitoringLazyRoute
  '/devices/cpus': typeof GuardLayoutDevicesCpusRoute
  '/devices/gpus': typeof GuardLayoutDevicesGpusRoute
  '/mining/algorithms': typeof GuardLayoutMiningAlgorithmsRoute
  '/mining/cryptocurrencies': typeof GuardLayoutMiningCryptocurrenciesRoute
  '/mining/miners': typeof GuardLayoutMiningMinersRoute
  '/mining/pools': typeof GuardLayoutMiningPoolsRoute
  '/mining/wallets': typeof GuardLayoutMiningWalletsRoute
  '/setup/flight-sheets': typeof GuardLayoutSetupFlightSheetsRoute
  '/setup/presets': typeof GuardLayoutSetupPresetsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_guard-layout': typeof GuardLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/registration': typeof AuthRegistrationRoute
  '/_guard-layout/monitoring': typeof GuardLayoutMonitoringLazyRoute
  '/_guard-layout/devices/cpus': typeof GuardLayoutDevicesCpusRoute
  '/_guard-layout/devices/gpus': typeof GuardLayoutDevicesGpusRoute
  '/_guard-layout/mining/algorithms': typeof GuardLayoutMiningAlgorithmsRoute
  '/_guard-layout/mining/cryptocurrencies': typeof GuardLayoutMiningCryptocurrenciesRoute
  '/_guard-layout/mining/miners': typeof GuardLayoutMiningMinersRoute
  '/_guard-layout/mining/pools': typeof GuardLayoutMiningPoolsRoute
  '/_guard-layout/mining/wallets': typeof GuardLayoutMiningWalletsRoute
  '/_guard-layout/setup/flight-sheets': typeof GuardLayoutSetupFlightSheetsRoute
  '/_guard-layout/setup/presets': typeof GuardLayoutSetupPresetsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/registration'
    | '/monitoring'
    | '/devices/cpus'
    | '/devices/gpus'
    | '/mining/algorithms'
    | '/mining/cryptocurrencies'
    | '/mining/miners'
    | '/mining/pools'
    | '/mining/wallets'
    | '/setup/flight-sheets'
    | '/setup/presets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/registration'
    | '/monitoring'
    | '/devices/cpus'
    | '/devices/gpus'
    | '/mining/algorithms'
    | '/mining/cryptocurrencies'
    | '/mining/miners'
    | '/mining/pools'
    | '/mining/wallets'
    | '/setup/flight-sheets'
    | '/setup/presets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guard-layout'
    | '/_auth/login'
    | '/_auth/registration'
    | '/_guard-layout/monitoring'
    | '/_guard-layout/devices/cpus'
    | '/_guard-layout/devices/gpus'
    | '/_guard-layout/mining/algorithms'
    | '/_guard-layout/mining/cryptocurrencies'
    | '/_guard-layout/mining/miners'
    | '/_guard-layout/mining/pools'
    | '/_guard-layout/mining/wallets'
    | '/_guard-layout/setup/flight-sheets'
    | '/_guard-layout/setup/presets'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  GuardLayoutRoute: typeof GuardLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  GuardLayoutRoute: GuardLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_guard-layout"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login",
        "/_auth/registration"
      ]
    },
    "/_guard-layout": {
      "filePath": "_guard-layout.tsx",
      "children": [
        "/_guard-layout/monitoring",
        "/_guard-layout/devices/cpus",
        "/_guard-layout/devices/gpus",
        "/_guard-layout/mining/algorithms",
        "/_guard-layout/mining/cryptocurrencies",
        "/_guard-layout/mining/miners",
        "/_guard-layout/mining/pools",
        "/_guard-layout/mining/wallets",
        "/_guard-layout/setup/flight-sheets",
        "/_guard-layout/setup/presets"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/registration": {
      "filePath": "_auth/registration.tsx",
      "parent": "/_auth"
    },
    "/_guard-layout/monitoring": {
      "filePath": "_guard-layout/monitoring.lazy.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/devices/cpus": {
      "filePath": "_guard-layout/devices/cpus.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/devices/gpus": {
      "filePath": "_guard-layout/devices/gpus.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/mining/algorithms": {
      "filePath": "_guard-layout/mining/algorithms.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/mining/cryptocurrencies": {
      "filePath": "_guard-layout/mining/cryptocurrencies.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/mining/miners": {
      "filePath": "_guard-layout/mining/miners.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/mining/pools": {
      "filePath": "_guard-layout/mining/pools.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/mining/wallets": {
      "filePath": "_guard-layout/mining/wallets.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/setup/flight-sheets": {
      "filePath": "_guard-layout/setup/flight-sheets.tsx",
      "parent": "/_guard-layout"
    },
    "/_guard-layout/setup/presets": {
      "filePath": "_guard-layout/setup/presets.tsx",
      "parent": "/_guard-layout"
    }
  }
}
ROUTE_MANIFEST_END */
